### ISSUE TITLE
BugTrap only uses first letter for anything

### ISSUE THREAD

**Issue by mattiascibien** [bchavez/BugTrap#16]
Hello,

I am using bugtrap for my C++ Unicode project and whenever I get a BugTrap Window I get only the first letter of the string I use for `BT_SetAppName`, `BT_SetSupportEMail`, `BT_SetSupportURL`.

Function is called like this

    BT_SetAppName(L"HELLO");

**Comment by nitrocaster** [comment]
Do you link Unicode version of BugTrap library?

**Comment by mattiascibien** [comment]
I tought it was not present in the latest release (only bugtrap.dll is present). So if this is the issue i will compile it myselft.

**Comment by nitrocaster** [comment]
Yeah, Unicode DLLs are completely missing from binary releases. Will fix.

**Comment by mattiascibien** [comment]
@nitrocaster thanks.
