### ISSUE TITLE
Obtaining the report .zip name (feature request) 

### ISSUE THREAD

**Issue by gvanem** [bchavez/BugTrap#17]
In a [curl-based](https://github.com/curl/curl) test-program I'm successfully using BugTrap to catch an exception and generate a .zip-file with a crash report. Then I try to use `curl` itself to upload that .zip to somewhere. An excerpt:

```
static const char *bt_ftp_host = "ftp://user:password@server/"; /* initialised elsewhere */
void CALLBACK ftp_put_error_log (INT_PTR unused);
void bugtrap_init (void)
{
  char buf [MAX_PATH];
  BT_SetAppName ("curl library");
  _snprintf (buf, sizeof(buf), "%s\\bugtrap-reports", getenv("TEMP"));
  BT_SetReportFilePath (buf);
  BT_SetActivityType (BTA_SAVEREPORT);
  BT_InstallSehFilter();
  BT_SetFlags (BTF_DETAILEDMODE | BTF_ATTACHREPORT);
  BT_SetReportFormat (BTRF_TEXT);
  BT_SetPostErrHandler (ftp_put_error_log, NULL);
}

void CALLBACK ftp_put_error_log (INT_PTR unused)
{
  char buf[MAX_PATH];
  _snprintf (buf, sizeof(buf), "curl -v --upload-file %s\\%s %s",
             BT_GetReportFilePath(), _what_should_be_here_, bt_ftp_host);
  printf ("executing: '%s'\n", buf);
  system  (buf);
}
```

My problem is how do I get the fully-qualified name of the `.zip`?
What is generated on runtime is `c:\TEMP\bugtrap-reports\curllibrary_snapshot_160205-081001.zip`. Unless I'm missing something, my _feature request_ and question is; how can that fully qualified name (`_what_should_be_here_`) be returned in the callback and passed to the `system()` function?

**Comment by bchavez** [comment]
@NeoAnomaly @gvanem The new release is up in the **Releases** tab. If you're satisfied with @NeoAnomaly 's PR and it resolves your issue feel free to close the issue.

Thanks everyone!
-Brian

**Comment by gvanem** [comment]
@bchavez  The PR is versatile. So I could solve my issue #17 using this. But feel it could be done much simpler.

**Comment by NeoAnomaly** [comment]
@gvanem hard for me to imagine a more simpler version :)

In your code:
`BT_SetActivityType (BTA_SAVEREPORT);`
is the same action as internal bugtrap logic, external handler also already defined:
```
void CALLBACK ftp_put_error_log (INT_PTR unused)
{
  ...
}
```

Change handler prototype, that's all.

**Comment by gvanem** [comment]
> Change handler prototype, that's all.

Ok, fine.

**Comment by gvanem** [comment]
@NeoAnomaly  I've tried to update my test-program for this PR. But the `.zip`-file seems to get deleted before my `BTA_CUSTOM` handler get called. I don't get it. An example would be nice..

**Comment by nitrocaster** [comment]
@gvanem `.zip` path which is passed to custom handler refers to temporary file. You can just copy it.
Why would you need more than 1 `BTA_x` types?

**Comment by gvanem** [comment]
@nitrocaster "*copy it*" or make it read-only with `_chmod()` is the same for me. I'll close this issue now.
