### ISSUE TITLE
Invalid address field in errorlog.xml

### ISSUE THREAD

**Issue by colindavidfoster** [bchavez/BugTrap#21]
More and more of our returned BugTrap reports have an `<address>` field containing 00000000 as follows
```
  <error>
    <what>ACCESS_VIOLATION</what>
    <process>
      <name>Designer.exe</name>
      <id>9476</id>
    </process>
    <module></module>
    <address>0023:00000000</address>
    <function>
      <name></name>
      <offset></offset>
    </function>
    <file></file>
    <line>
      <number></number>
      <offset></offset>
    </line>
  </error>
```
Probably not surprisingly this causes CrashExplorer to crash.

These apparently useless reports have prompted me to look into updating from version 1.3.3718.38316 to the latest version. Can anyone offer a reason why 00000000 should could appear in an errorlog.xml file? Furthermore, if this has been a known problem, is it fixed in the latest version?

**Comment by nitrocaster** [comment]
Zero address is not something unusual - it appears when your code calls a function by zero pointer:

    void(*func)(void) = NULL;
    func();

What us definitely bad is that CrashExplorer crashes. If you still have those reports, could you try open them with latest CrashExplorer to see if it crashes again?

**Comment by colindavidfoster** [comment]
Yes CrashExplorer just sits there saying Please Wait, It looks like it is doing exceptions in the background

First-chance exception at 0x900008c2 in CrashExplorer.exe: 0xC0000005: Access violation.
First-chance exception at 0x00000200 in CrashExplorer.exe: 0xC0000005: Access violation.
First-chance exception at 0x900008c2 in CrashExplorer.exe: 0xC0000005: Access violation.
First-chance exception at 0x00000200 in CrashExplorer.exe: 0xC0000005: Access violation.
First-chance exception at 0x900008c2 in CrashExplorer.exe: 0xC0000005: Access violation.

If I upload the map, pdb, xml and dmp files can I be sure that they can only be downloaded by BugTrap administrators?

**Comment by nitrocaster** [comment]
No, they would be in public access. You can email me these files and I'll try to figure out what is the problem.

**Comment by colindavidfoster** [comment]
Did you get the zip file I sent?

**Comment by nitrocaster** [comment]
Yes, I did. I'll take care of it this weekend and let you know what I found out.

**Comment by nitrocaster** [comment]
I guess that was a typo. Apparently nobody ever loaded reports with MAP file.

**Comment by bchavez** [comment]
Thanks for looking into this @nitrocaster !

@colindavidfoster , does the `v1.4.8` release with @nitrocaster 's patch your issue?

**Comment by colindavidfoster** [comment]
Yes, though I was thrown for a while because I tried the new version in debug mode and my (large) map file was taking ages to load in CMapProcessor::GetPublicFunctions(). Of course when I changed to release things were a lot faster.

Now I've got to look at why the VS2008 solution won't build for me. I suspect it's a build environment issue on my PC. I may come back to you if I can't resolve it.

Thanks

**Comment by colindavidfoster** [comment]
PS. I had to make a couple of small changes to the vs2013 solution/project to get it to build. Firstly to add boost to the list of link libraries. That's not surprising because we don't run with boost in our default libraries. However, I had to fiddle around to find <atlapp.h>. Presumably this is because I don't have some prerequisite SDK installed
