### ISSUE TITLE
Error using BT_SetReportFormat (BTRF_TEXT) in x64 build

### ISSUE THREAD

**Issue by rush2ko** [bchavez/BugTrap#22]
BT_SetReportFormat(BTRF_XML) is ok.
minidump & report are complete.
But,
You can not create a minidump file when using BT_SetReportFormat (BTRF_TEXT) at x64 build time.
Example)

        TCHAR szBuf[1024];
	GetCurrentDirectoryW(1024, szBuf);
	_tcscat_s(szBuf, 1024, _T("/dump"));
	BT_InstallSehFilter();
	BT_SetAppVersion(_T("1.0"));
	BT_SetAppName(_T("sample"));
	BT_SetFlags(BTF_DETAILEDMODE);
	BT_SetReportFilePath(szBuf);
	BT_SetActivityType(BTA_SAVEREPORT);
	BT_SetReportFormat(BTRF_TEXT);
	BT_SetPreErrHandler((BT_ErrHandler)ExceptionHandler, 0);
	BT_SetDumpType(0x00000001 | 0x00000040);

**Comment by bchavez** [comment]
I think @NeoAnomaly 's PR #26 fixes this issue. Feel free to reopen the issue if it continues to be a problem.

The fix for this issue will be available in `v1.4.9`.

/cc @Xottab-DUTY

**Comment by Xottab-DUTY** [comment]
Well. It seems, that issue isn't fixed. While BugTrap can create report, it's still not creating a dump file.

**Comment by NeoAnomaly** [comment]
@Xottab-DUTY do you have project that doesn't work? Can you confirm next sentence?
>BT_SetReportFormat(BTRF_XML) is ok.
>You can not create a minidump file when using BT_SetReportFormat (BTRF_TEXT) at x64 build time.

Or other conditions may be presented to reproduce the error.

**Comment by Xottab-DUTY** [comment]
The project is [here](https://github.com/Xottab-DUTY/xray-16).

We are using BTRF_TEXT as a report format, BT_SetDumpType flags is the same (0x00000001 | 0x00000040)

Will check BTRF_XML later.

**Comment by Xottab-DUTY** [comment]
Hmm.... now it started to create minudump with BTRF_TEXT... Well. I'll will continue testing further

**Comment by NeoAnomaly** [comment]
Ok, I'll continue investigating the problem.

**Comment by Xottab-DUTY** [comment]
Release build of the project will be published soon so that users can test it and we can find out if BugTrap creating dumps or there's problems with it.
