### ISSUE TITLE
VersionInfo.h has wrong version

### ISSUE THREAD

**Issue by steno916** [bchavez/BugTrap#27]
VersionInfo.h needs to be updated to reflect the correct version number.

**Comment by bchavez** [comment]
Hi @steno916 ,

Thanks for your issue. IIRC, `VersionInfo.h` is managed by the build system.  The primary reason we're not "hand editing" `VersionInfo.h` is mostly that of a maintenance issue. It's really easy to forget to "update" version number files before a build/release. The build server is the one that manages the correct build numbers in `VersionInfo.h` whenever there is a tagged repo release.

https://github.com/bchavez/BugTrap/blob/4f540fd020b3363d8624675619420f217ba4febc/appveyor.yml#L22-L50

If you find there's some other `VersionInfo.h` that needs to be part of the build process, feel free to modify the file and send us a PR. Or, perhaps we should set these to `0.0.0.1` to better indicate this.

Thanks,
Brian

**Comment by bchavez** [comment]
Resolved this in 39c19840257de6273d1b481998f204ed50428f80. The version number in the source is `0.0.0.1`, the actual build number is managed by the CI server via Git version tag.
