### ISSUE TITLE
BugTrap own mail client

### ISSUE THREAD

**Issue by Xottab-DUTY** [bchavez/BugTrap#30]
Currently if a user doesn't have any mail client installed, BugTrap can't send report to support email.

**Comment by NeoAnomaly** [comment]
@Xottab-DUTY, are you knowing the host/port/username/pass of your server? In my mind, If you haven't had an email client on your computer yet then you have used a web-client. 

It take you to save a bug report then send it with a web-client or try to remeber the all needed e-mail server params. Which is easier?

**Comment by Xottab-DUTY** [comment]
Not sure that I understand you correctly. I have no support server but an email.

If user's system doesn't have registered default program for email, then clicking on Submit Bug leads to nothing. System says that there is no program for email and BugTrap fails to send report..

**Comment by NeoAnomaly** [comment]
I mean, to send an email you gotta use an email server(smtp). Own mail client will take user to enter an email server settings(minimum 4 values I wrote above).
